Hello Microverse project day2 pull request
byiringiroscar/Hello-Microverse pull request #1
Opened 2023-01-10 20:56 UTC by byiringiroscar

it is project related to HTML and CSS project

2023-01-11 11:23 UTC, brainconnect93 requested changes
### Hi @byiringiroscar, 👋 

# STATUS: Changes Required :recycle:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/kghYzGafFW0AAAAM/almost-paul-walker.gif">

### To Highlight :1st_place_medal: 
-  Has a proper Pull Request. ✔️  
- No Linter errors :heavy_check_mark: 
- Good use of Github flow ✔️ 

### Changes Required

- [ ] 🚧 Please let's always avoid working directly on the master/main branch and always use the feature branch and then make a pull request to the main/master branch. I could see you already have almost all the new changes in the master branch.

The master branch often reflects the code used in production. Hence, it is not a good practice to commit your work to the master branch. It is recommended to branch out or create a copy of the master branch in a different branch where you will commit your work. [learn more](https://www.becomebetterprogrammer.com/is-it-bad-to-commit-to-master-branch-why-senior-engineers-advice/#:~:text=Master%20branch%20often%20reflects%20the,you%20will%20commit%20your%20work.)

- [ ] 🚧 Please make sure to include a LICENSE to your project, at the moment this is not working. Microverse suggests you use the MIT one. Follow the [official docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to achieve this! 🤓

Public repositories on GitHub are often used to share open-source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

- [ ] I notice some of your files are missing on the `htmlcss-branch` kindly pull the files from the `main branch` to the current branch you are working on.

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-11 11:23 UTC, brainconnect93 commented on style.css
> +h1 { color: brown; }
- [ ] Kindly use the class name given to your h1 tag to style the content

E.g
```CSS
.title {
  color: brown;
}
```

2023-01-11 14:57 UTC, Abdessittir requested changes
Hi @byiringiroscar, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

 ## Highlights
✅ Good commit messages
✅ No linter errors
✅ Good GitHub Flow

 ## Required Changes ♻️
- [ ] White you did a great job by adding MIT LICENSE to your project, but you still have
 to add a link to it in The readme file because it's included in the Readme template like this:

![MIT](https://user-images.githubusercontent.com/95412943/211838675-f051f098-3cd8-4172-9dda-8b7cd9596b41.PNG)

## Optional suggestions
 - [OPTIONAL] check the comments below
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-11 14:57 UTC, Abdessittir commented on README.md
> +> Hello-Microverse is project for microverse day 2 where aims is to be interacting with github and be able to use linter.
- [OPTIONAL] Kindly remove this line because it's just an instruction of what you can put in this section

2023-01-11 14:57 UTC, Abdessittir commented on README.md
> +> Describe the tech stack and include only the relevant sections that apply to your project.
[OPTIONAL] Kindly remove this line because it's just an instruction of what you can put in this section

2023-01-11 14:57 UTC, Abdessittir commented on README.md
> +> This project show how we can interact with github and linter.
[OPTIONAL] Kindly remove this line because it's just an instruction of what you can put in this section

2023-01-11 14:57 UTC, Abdessittir commented on README.md
> +> Mention all of the collaborators of this project.
[OPTIONAL] Kindly remove this line because it's just an instruction of what you can put in this section

2023-01-11 16:11 UTC, Abdessittir approved these changes
Hi @byiringiroscar, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights
✅ Good commit messages
✅ Good GitHub Flow
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 10:57 UTC, merged

2023-01-12 10:58 UTC, byiringiroscar commented
finishing to merge my first project in microverse